name: Deno Scraper Job

on:
  # push:
  #   branches: ["main"]
  # pull_request:
  #   branches: ["main"]
  schedule:
    - cron: '0 5 1 * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_download:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      
      - name: Test the scraper script
        run: deno run test

      - name: Run the scraper script
        run: deno run start

      - name: Archive events files
        uses: actions/upload-artifact@v4
        with:
          name: events_files
          path: dist
      
      - name: Archive parse error logs
        uses: actions/upload-artifact@v4
        with:
          name: parse_log.txt
          path: parse_log.txt
        
